<html>
<head>
    <title>Logowanie</title>

    <link rel="stylesheet" type="text/css" media="screen" href="/css/style_index.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="/css/bootstrap.css" />
    <script src="/js/jquery-2.2.4.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/index.js"></script>
    <script src="/js/moj.js"></script>
</head>

<body>

<?= $this->content; ?>

</body>

</html>